#!/usr/bin/env python3
"""
DESCRIPTION:
Compile ONNX models into TensorRT engines optimised for the Jetson Orin Nano.


OUTPUT:
For every .onnx file found under models/<FOLDER>/*/ two engines are written:

    <stem>_fp16.engine  — 16-bit float  (half the memory of FP32, ~same accuracy)
    <stem>_int8.engine  — 8-bit integer (smallest and fastest; needs calibration)

INFORMATION:
    INT8 CALIBRATION CACHE  (in priority order)

    1. --calib <file>         explicit cache path passed on the command line
    2. <model_dir>/<stem>.cache  per-model cache auto-detected next to the ONNX
                              (generated by calibration_cache.py — run it first)
    3. No cache               trtexec uses random data; accuracy will be reduced


USAGE:
    python onnx2engine.py [--folder FOLDER] [--calib CALIB_CACHE]
"""



# ==========================================================================
#                                IMPORTS                      
# ==========================================================================
import argparse
import subprocess
import sys
from pathlib import Path


# ==========================================================================
#                                CONFIG
# ==========================================================================

# Which sub-folder inside ./models/ to process (pass --folder to override)
FOLDER = "v1"

# GPU workspace budget for TensorRT's layer-fusion optimiser.
# 4 GiB is safe for the Orin Nano's 8 GiB unified RAM.
WORKSPACE_MB = 4096

# trtexec must be on PATH (ships with the TensorRT SDK and Jetson JetPack)
TRTEXEC = "trtexec"



# trtexec flags shared across every engine build
# These are tuned for the Jetson Orin Nano

BASE_FLAGS = [
    # How much GPU memory TensorRT can use while optimising the graph
    f"--memPoolSize=workspace:{WORKSPACE_MB}MiB",

    # Enable all three fast-math backends so TensorRT can pick the fastest
    # kernel for each layer: cuBLAS, cuBLAS-LT (lightweight), and cuDNN
    "--tacticSources=+CUBLAS,+CUBLAS_LT,+CUDNN",

    # Measure only compute time, not data-transfer overhead.
    # On Jetson the CPU and GPU share memory, so transfers are cheap anyway.
    "--noDataTransfers",

    # TRT 8.5+ optimisation that speeds up models with dynamic input shapes
    "--preview=+fasterDynamicShapes0805",
]




# ==========================================================================
#                                CONFIG
# ==========================================================================

# Engine builders ----------------------------------------------------------
def _run_trtexec(cmd: list[str]) -> bool:
    """
    Run a trtexec command, streaming its output live to the terminal.
    Returns True if the command exited successfully, False otherwise.
    """
    print("  $", " ".join(cmd))
    result = subprocess.run(cmd)
    return result.returncode == 0


def build_fp16_engine(onnx_path: Path, output_path: Path) -> bool:
    """
    Compile an FP16 TensorRT engine from an ONNX model.

    FP16 halves the memory footprint versus FP32 with negligible accuracy
    loss for most regression and classification tasks.
    """
    return _run_trtexec([
        TRTEXEC,
        f"--onnx={onnx_path}",
        f"--saveEngine={output_path}",
        "--fp16",
        *BASE_FLAGS,
    ])


def build_int8_engine(onnx_path: Path, output_path: Path, calib_cache: Path | None) -> bool:
    """
    Compile an INT8 TensorRT engine from an ONNX model.

    INT8 is the fastest and smallest option — roughly 4× faster than FP32
    on Ampere — but it needs calibration data to choose accurate scale
    factors.  FP16 is also enabled here as a fallback for any layers that
    TensorRT cannot run in INT8 (e.g. some normalisation layers).

    If calib_cache is None, trtexec will calibrate with random data, which
    typically hurts accuracy.  Run calibration_cache.py first to avoid this.
    """
    flags = [
        "--int8",
        "--fp16",   # fallback for INT8-unsupported layers
        *BASE_FLAGS,
    ]
    if calib_cache:
        flags.append(f"--calib={calib_cache}")

    return _run_trtexec([
        TRTEXEC,
        f"--onnx={onnx_path}",
        f"--saveEngine={output_path}",
        *flags,
    ])



# Entry point ---------------------------------------------------------------

def main() -> None:
    arg_parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    arg_parser.add_argument(
        "--folder", default=FOLDER,
        help="Sub-folder inside ./models/  (default: %(default)s)",
    )
    arg_parser.add_argument(
        "--calib", type=Path, default=None,
        help="INT8 calibration cache - overrides the per-model auto-detected cache",
    )
    args = arg_parser.parse_args()

    repo_root  = Path(__file__).resolve().parents[2]
    models_dir = repo_root / "models" / args.folder

    if not models_dir.exists():
        print(f"ERROR: models directory not found: {models_dir}", file=sys.stderr)
        sys.exit(1)

    onnx_files = sorted(models_dir.glob("*/*.onnx"))
    if not onnx_files:
        print(f"ERROR: no .onnx files found under {models_dir}", file=sys.stderr)
        sys.exit(1)

    print(f"Found {len(onnx_files)} model(s) in {models_dir}\n")

    results: dict[str, dict[str, bool]] = {}

    for onnx_path in onnx_files:
        model_name = onnx_path.stem
        output_dir = onnx_path.parent

        print(f"{'-' * 60}")
        print(f"  Model : {model_name}")
        print(f"  Source: {onnx_path.relative_to(repo_root)}")
        print()

        # FP16 engine
        fp16_output = output_dir / f"{model_name}_fp16.engine"
        print(f"  [FP16] Building -> {fp16_output.name}")
        fp16_ok = build_fp16_engine(onnx_path, fp16_output)
        print(f"  [FP16] {'OK' if fp16_ok else 'FAIL'}\n")

        # INT8 engine
        int8_output  = output_dir / f"{model_name}_int8.engine"
        auto_cache   = output_dir / f"{model_name}.cache"

        # Pick the best available calibration cache.
        # Command-line flag takes priority / otherwise look for the per-model
        # cache that calibration_cache.py writes next to the ONNX file.
        calib_cache = args.calib or (auto_cache if auto_cache.exists() else None)

        print(f"  [INT8] Building -> {int8_output.name}")
        if calib_cache:
            print(f"  [INT8] Using calibration cache: {calib_cache.name}")
        else:
            print("  [INT8] WARNING: no calibration cache found - INT8 accuracy may be poor")
            print("         Tip: run calibration_cache.py first for best results")

        int8_ok = build_int8_engine(onnx_path, int8_output, calib_cache)
        print(f"  [INT8] {'OK' if int8_ok else 'FAIL'}\n")

        results[model_name] = {"fp16": fp16_ok, "int8": int8_ok}


    # Final summary 
    print(f"{'═' * 60}")
    print("  Summary")
    print(f"{'─' * 60}")
    all_ok = True
    for model_name, res in results.items():
        fp16_sym = "OK" if res["fp16"] else "FAIL"
        int8_sym = "OK" if res["int8"] else "FAIL"
        print(f"  {model_name:<20}  FP16 {fp16_sym}   INT8 {int8_sym}")
        all_ok = all_ok and all(res.values())
    print(f"{'═' * 60}")

    sys.exit(0 if all_ok else 1)


if __name__ == "__main__":
    main()
